//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajadores
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateTrabajadores
    {
        public int id_Trabajadores { get; set; }
        public string Nombre { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public Nullable<double> Edad { get; set; }
        public string Sexo { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Area { get; set; }
        public Nullable<System.TimeSpan> Hora_Entrada { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
    }
}
